spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/sky_connect
spring.datasource.username=root
spring.datasource.password=Bhavani-28

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# ===============================
# AirLabs Flight API
# ===============================

airlabs.api.url=https://airlabs.co/api/v9
airlabs.api.key=50dfc56e-fa63-49d6-a317-06916a87aba5

spring.jpa.properties.hibernate.format_sql=true


# ==========================================
# GMAIL SMTP CONFIGURATION
# ==========================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=bhavani.s0628@gmail.com
spring.mail.password=fepv vdah fvxx qfqz

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
# JWT
jwt.secret=SkyConnectJWTSecretKeyForAuthentication2026VerySecureKey123456789

# 24 hours
jwt.expiration=86400000

spring.jpa.open-in-view=false
server.port=8080